// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4yvFBn29I7bRMLdSTckW23HajJrJgc4',
    appId: '1:811055477409:web:87dd6d23a0447c9ff676e0',
    messagingSenderId: '811055477409',
    projectId: 'agenda-digital-c462d',
    authDomain: 'agenda-digital-c462d.firebaseapp.com',
    storageBucket: 'agenda-digital-c462d.appspot.com',
    measurementId: 'G-M0PXBW1TX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVvJdhfIpX-40urX2_sM_uioJmc48DUzo',
    appId: '1:811055477409:android:13e408c0a68cf0ebf676e0',
    messagingSenderId: '811055477409',
    projectId: 'agenda-digital-c462d',
    storageBucket: 'agenda-digital-c462d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj164DpoFiuIrA80fYqqK-RrY5Gu-Z8fg',
    appId: '1:811055477409:ios:aee062a0a890b05df676e0',
    messagingSenderId: '811055477409',
    projectId: 'agenda-digital-c462d',
    storageBucket: 'agenda-digital-c462d.appspot.com',
    iosBundleId: 'mx.edu.ittepic.agendaDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj164DpoFiuIrA80fYqqK-RrY5Gu-Z8fg',
    appId: '1:811055477409:ios:9910c83c3cc2d60df676e0',
    messagingSenderId: '811055477409',
    projectId: 'agenda-digital-c462d',
    storageBucket: 'agenda-digital-c462d.appspot.com',
    iosBundleId: 'mx.edu.ittepic.agendaDigital.RunnerTests',
  );
}
